_BASE_: "Base-CenterMask-VoVNet.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/1mlv31coewx8trd/vovnet99_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-99-eSE"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "/home/ubuntu/output/centermask/CenterMask-V-99-ms-3x"
DATASETS:
  TRAIN: ("path_train",)
  TEST: ("path_val",)
SOLVER:
  CHECKPOINT_PERIOD: 20000 #10000
  IMS_PER_BATCH: 2 #16
  BASE_LR: 0.0005  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 200000
  

